// tag.ts

export interface TagSeedData {
  id: string;
  name: string;
  description: string;
  parentId: string | null;
  level: number;
  taxonomyTypeCode: string; // "INDUSTRY" | "JOB_CATEGORY" | "POSITION" | "SITUATION" | "SKILL_METHOD" | "KNOWLEDGE"
  sortOrder: number;
}

/**
 * 命名ルール（衝突回避）
 * - id は taxonomy ごとに prefix を付与（industry- / job- / position- / situation- / skill- / knowledge-）
 * - 階層は parentId で表現
 * - sortOrder は同一 parentId 内で 1.. の並び
 *
 * 階層レベル
 * - ルート（例: 業界/職種/役割…）: level=1
 * - 以降は +1
 */
export const tagSeedData: TagSeedData[] = [
  // =========================================================
  // 業界
  // =========================================================    
  {
    id: "industry-it-internet",
    name: "IT・インターネット",
    description: "IT、ソフトウェア、インターネット関連",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "INDUSTRY",
    sortOrder: 1,
  },
  {
    id: "industry-consulting-professional",
    name: "コンサルティング・専門サービス",
    description: "コンサル・士業などの専門サービス",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "INDUSTRY",
    sortOrder: 2,
  },
  {
    id: "industry-manufacturing",
    name: "メーカー（製造業）",
    description: "製造業（ハイテク/素材/ライフスタイル等）",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "INDUSTRY",
    sortOrder: 3,
  },
  {
    id: "industry-trading-retail",
    name: "商社・流通・小売",
    description: "商社、流通、小売、外食、店舗ビジネスなど",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "INDUSTRY",
    sortOrder: 4,
  },
  {
    id: "industry-finance-insurance",
    name: "金融・保険",
    description: "銀行、証券、保険、FinTechなど",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "INDUSTRY",
    sortOrder: 5,
  },
  {
    id: "industry-realestate-construction-infra",
    name: "不動産・建設・インフラ",
    description: "不動産、建設、土木、物流など",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "INDUSTRY",
    sortOrder: 6,
  },
  {
    id: "industry-ad-media-entertainment",
    name: "広告・メディア・エンタメ",
    description: "広告、出版、映像、ゲームなど",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "INDUSTRY",
    sortOrder: 7,
  },
  {
    id: "industry-medical-healthcare",
    name: "メディカル・ヘルスケア",
    description: "医薬品、医療機器、病院、介護など",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "INDUSTRY",
    sortOrder: 8,
  },
  {
    id: "industry-service-hr",
    name: "サービス・人材",
    description: "人材、教育、旅行、BPOなど",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "INDUSTRY",
    sortOrder: 9,
  },
  {
    id: "industry-public-other",
    name: "公共・その他",
    description: "官公庁、NPO、一次産業など",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "INDUSTRY",
    sortOrder: 10,
  },

  // 2階層 - IT・インターネット
  {
    id: "industry-it-internet-internet-services-ec",
    name: "インターネットサービス・EC",
    description: "Webサービス・EC事業",
    parentId: "industry-it-internet",
    level: 2,
    taxonomyTypeCode: "INDUSTRY",
    sortOrder: 1,
  },
  {
    id: "industry-it-internet-saas-software",
    name: "SaaS・ソフトウェア",
    description: "SaaS/ソフトウェア開発・提供",
    parentId: "industry-it-internet",
    level: 2,
    taxonomyTypeCode: "INDUSTRY",
    sortOrder: 2,
  },
  {
    id: "industry-it-internet-digital-marketing",
    name: "デジタルマーケティング",
    description: "広告/マーケティング支援（デジタル）",
    parentId: "industry-it-internet",
    level: 2,
    taxonomyTypeCode: "INDUSTRY",
    sortOrder: 3,
  },
  {
    id: "industry-it-internet-ai-data-science",
    name: "AI・データサイエンス",
    description: "AI/データ活用・分析関連",
    parentId: "industry-it-internet",
    level: 2,
    taxonomyTypeCode: "INDUSTRY",
    sortOrder: 4,
  },
  {
    id: "industry-it-internet-telecom-infra",
    name: "通信・インフラ",
    description: "通信事業者/インフラサービス",
    parentId: "industry-it-internet",
    level: 2,
    taxonomyTypeCode: "INDUSTRY",
    sortOrder: 5,
  },

  // 2階層 - コンサルティング・専門サービス
  {
    id: "industry-consulting-professional-strategy-management-consulting",
    name: "戦略・経営コンサルティング",
    description: "経営戦略/事業戦略支援",
    parentId: "industry-consulting-professional",
    level: 2,
    taxonomyTypeCode: "INDUSTRY",
    sortOrder: 1,
  },
  {
    id: "industry-consulting-professional-operations-it-consulting",
    name: "業務・ITコンサルティング",
    description: "業務改革/IT導入支援",
    parentId: "industry-consulting-professional",
    level: 2,
    taxonomyTypeCode: "INDUSTRY",
    sortOrder: 2,
  },
  {
    id: "industry-consulting-professional-research-thinktank",
    name: "リサーチ・シンクタンク",
    description: "調査/政策/市場分析など",
    parentId: "industry-consulting-professional",
    level: 2,
    taxonomyTypeCode: "INDUSTRY",
    sortOrder: 3,
  },
  {
    id: "industry-consulting-professional-audit-tax-firm",
    name: "監査法人・税理士法人",
    description: "監査/税務の専門法人",
    parentId: "industry-consulting-professional",
    level: 2,
    taxonomyTypeCode: "INDUSTRY",
    sortOrder: 4,
  },
  {
    id: "industry-consulting-professional-law-ip-firm",
    name: "法律事務所・知財特許事務所",
    description: "法律/知財・特許の専門事務所",
    parentId: "industry-consulting-professional",
    level: 2,
    taxonomyTypeCode: "INDUSTRY",
    sortOrder: 5,
  },

  // 2階層 - メーカー（製造業）
  {
    id: "industry-manufacturing-hightech-machinery",
    name: "ハイテク・機械",
    description: "電機/自動車/精密機器など",
    parentId: "industry-manufacturing",
    level: 2,
    taxonomyTypeCode: "INDUSTRY",
    sortOrder: 1,
  },
  {
    id: "industry-manufacturing-material-energy",
    name: "素材・エネルギー",
    description: "化学/素材/電力/ガス等",
    parentId: "industry-manufacturing",
    level: 2,
    taxonomyTypeCode: "INDUSTRY",
    sortOrder: 2,
  },
  {
    id: "industry-manufacturing-lifestyle",
    name: "ライフスタイル",
    description: "食品/日用品/アパレル等",
    parentId: "industry-manufacturing",
    level: 2,
    taxonomyTypeCode: "INDUSTRY",
    sortOrder: 3,
  },

  // 3階層 - ハイテク・機械
  {
    id: "industry-manufacturing-hightech-machinery-electronics-semiconductor",
    name: "電気・電子・半導体",
    description: "電機/電子部品/半導体",
    parentId: "industry-manufacturing-hightech-machinery",
    level: 3,
    taxonomyTypeCode: "INDUSTRY",
    sortOrder: 1,
  },
  {
    id: "industry-manufacturing-hightech-machinery-automotive-transport",
    name: "自動車・輸送機器",
    description: "自動車/輸送機器メーカー",
    parentId: "industry-manufacturing-hightech-machinery",
    level: 3,
    taxonomyTypeCode: "INDUSTRY",
    sortOrder: 2,
  },
  {
    id: "industry-manufacturing-hightech-machinery-precision-machine-tools",
    name: "精密機器・工作機械",
    description: "精密機器/工作機械メーカー",
    parentId: "industry-manufacturing-hightech-machinery",
    level: 3,
    taxonomyTypeCode: "INDUSTRY",
    sortOrder: 3,
  },

  // 3階層 - 素材・エネルギー
  {
    id: "industry-manufacturing-material-energy-chemical-oil-materials",
    name: "化学・石油・素材",
    description: "化学/石油/素材メーカー",
    parentId: "industry-manufacturing-material-energy",
    level: 3,
    taxonomyTypeCode: "INDUSTRY",
    sortOrder: 1,
  },
  {
    id: "industry-manufacturing-material-energy-utilities",
    name: "電力・ガス・水道",
    description: "公益インフラ（電力/ガス/水道）",
    parentId: "industry-manufacturing-material-energy",
    level: 3,
    taxonomyTypeCode: "INDUSTRY",
    sortOrder: 2,
  },

  // 3階層 - ライフスタイル
  {
    id: "industry-manufacturing-lifestyle-food-beverage",
    name: "食品・飲料",
    description: "食品/飲料メーカー",
    parentId: "industry-manufacturing-lifestyle",
    level: 3,
    taxonomyTypeCode: "INDUSTRY",
    sortOrder: 1,
  },
  {
    id: "industry-manufacturing-lifestyle-daily-cosmetics",
    name: "日用品・化粧品",
    description: "日用品/化粧品メーカー",
    parentId: "industry-manufacturing-lifestyle",
    level: 3,
    taxonomyTypeCode: "INDUSTRY",
    sortOrder: 2,
  },
  {
    id: "industry-manufacturing-lifestyle-apparel-goods",
    name: "アパレル・雑貨",
    description: "衣料品/雑貨メーカー",
    parentId: "industry-manufacturing-lifestyle",
    level: 3,
    taxonomyTypeCode: "INDUSTRY",
    sortOrder: 3,
  },

  // 2階層 - 商社・流通・小売
  {
    id: "industry-trading-retail-general-trading",
    name: "総合商社",
    description: "総合商社",
    parentId: "industry-trading-retail",
    level: 2,
    taxonomyTypeCode: "INDUSTRY",
    sortOrder: 1,
  },
  {
    id: "industry-trading-retail-specialized-trading",
    name: "専門商社",
    description: "専門領域の商社",
    parentId: "industry-trading-retail",
    level: 2,
    taxonomyTypeCode: "INDUSTRY",
    sortOrder: 2,
  },
  {
    id: "industry-trading-retail-retail-distribution",
    name: "小売・流通",
    description: "小売/流通事業",
    parentId: "industry-trading-retail",
    level: 2,
    taxonomyTypeCode: "INDUSTRY",
    sortOrder: 3,
  },
  {
    id: "industry-trading-retail-restaurant",
    name: "外食",
    description: "飲食チェーン/外食産業",
    parentId: "industry-trading-retail",
    level: 2,
    taxonomyTypeCode: "INDUSTRY",
    sortOrder: 4,
  },
  {
    id: "industry-trading-retail-store-business",
    name: "店舗ビジネス",
    description: "店舗運営を中心とした事業",
    parentId: "industry-trading-retail",
    level: 2,
    taxonomyTypeCode: "INDUSTRY",
    sortOrder: 5,
  },
  {
    id: "industry-trading-retail-ecommerce",
    name: "Eコマース・通販",
    description: "EC/通販事業",
    parentId: "industry-trading-retail",
    level: 2,
    taxonomyTypeCode: "INDUSTRY",
    sortOrder: 6,
  },

  // 2階層 - 金融・保険
  {
    id: "industry-finance-insurance-bank",
    name: "銀行",
    description: "銀行（メガ/地銀等）",
    parentId: "industry-finance-insurance",
    level: 2,
    taxonomyTypeCode: "INDUSTRY",
    sortOrder: 1,
  },
  {
    id: "industry-finance-insurance-securities",
    name: "証券",
    description: "証券会社",
    parentId: "industry-finance-insurance",
    level: 2,
    taxonomyTypeCode: "INDUSTRY",
    sortOrder: 2,
  },
  {
    id: "industry-finance-insurance-trust",
    name: "信託",
    description: "信託銀行/信託業務",
    parentId: "industry-finance-insurance",
    level: 2,
    taxonomyTypeCode: "INDUSTRY",
    sortOrder: 3,
  },
  {
    id: "industry-finance-insurance-credit-union",
    name: "信用金庫・信用組合",
    description: "信用金庫/信用組合",
    parentId: "industry-finance-insurance",
    level: 2,
    taxonomyTypeCode: "INDUSTRY",
    sortOrder: 4,
  },
  {
    id: "industry-finance-insurance-ib-vc-pe",
    name: "投資銀行・VC・PEファンド",
    description: "投資銀行/VC/PE等",
    parentId: "industry-finance-insurance",
    level: 2,
    taxonomyTypeCode: "INDUSTRY",
    sortOrder: 5,
  },
  {
    id: "industry-finance-insurance-payment-fintech",
    name: "決済・FinTech",
    description: "決済/FinTech",
    parentId: "industry-finance-insurance",
    level: 2,
    taxonomyTypeCode: "INDUSTRY",
    sortOrder: 6,
  },
  {
    id: "industry-finance-insurance-life-insurance",
    name: "生命保険",
    description: "生命保険会社",
    parentId: "industry-finance-insurance",
    level: 2,
    taxonomyTypeCode: "INDUSTRY",
    sortOrder: 7,
  },
  {
    id: "industry-finance-insurance-nonlife-insurance",
    name: "損害保険",
    description: "損害保険会社",
    parentId: "industry-finance-insurance",
    level: 2,
    taxonomyTypeCode: "INDUSTRY",
    sortOrder: 8,
  },

  // 2階層 - 不動産・建設・インフラ
  {
    id: "industry-realestate-construction-infra-developer",
    name: "デベロッパー",
    description: "不動産開発（デベロッパー）",
    parentId: "industry-realestate-construction-infra",
    level: 2,
    taxonomyTypeCode: "INDUSTRY",
    sortOrder: 1,
  },
  {
    id: "industry-realestate-construction-infra-house-maker",
    name: "ハウスメーカー",
    description: "住宅メーカー",
    parentId: "industry-realestate-construction-infra",
    level: 2,
    taxonomyTypeCode: "INDUSTRY",
    sortOrder: 2,
  },
  {
    id: "industry-realestate-construction-infra-realestate-brokerage",
    name: "不動産仲介",
    description: "不動産仲介業",
    parentId: "industry-realestate-construction-infra",
    level: 2,
    taxonomyTypeCode: "INDUSTRY",
    sortOrder: 3,
  },
  {
    id: "industry-realestate-construction-infra-property-management",
    name: "管理",
    description: "不動産管理（PM/ビル管理等）",
    parentId: "industry-realestate-construction-infra",
    level: 2,
    taxonomyTypeCode: "INDUSTRY",
    sortOrder: 4,
  },
  {
    id: "industry-realestate-construction-infra-construction-civil-design",
    name: "建設・土木・設計",
    description: "建設/土木/設計",
    parentId: "industry-realestate-construction-infra",
    level: 2,
    taxonomyTypeCode: "INDUSTRY",
    sortOrder: 5,
  },
  {
    id: "industry-realestate-construction-infra-plant-engineering",
    name: "プラント・エンジニアリング",
    description: "プラント建設/エンジニアリング",
    parentId: "industry-realestate-construction-infra",
    level: 2,
    taxonomyTypeCode: "INDUSTRY",
    sortOrder: 6,
  },
  {
    id: "industry-realestate-construction-infra-logistics-warehouse-transport",
    name: "物流・倉庫・運輸",
    description: "物流/倉庫/運輸",
    parentId: "industry-realestate-construction-infra",
    level: 2,
    taxonomyTypeCode: "INDUSTRY",
    sortOrder: 7,
  },

  // 2階層 - 広告・メディア・エンタメ
  {
    id: "industry-ad-media-entertainment-agency-pr",
    name: "広告代理店・PR",
    description: "広告代理店/PR会社",
    parentId: "industry-ad-media-entertainment",
    level: 2,
    taxonomyTypeCode: "INDUSTRY",
    sortOrder: 1,
  },
  {
    id: "industry-ad-media-entertainment-tv-news-publishing",
    name: "テレビ・新聞・出版",
    description: "放送/新聞/出版",
    parentId: "industry-ad-media-entertainment",
    level: 2,
    taxonomyTypeCode: "INDUSTRY",
    sortOrder: 2,
  },
  {
    id: "industry-ad-media-entertainment-film-music-video-production",
    name: "映画・音楽・映像制作",
    description: "映像/音楽/制作",
    parentId: "industry-ad-media-entertainment",
    level: 2,
    taxonomyTypeCode: "INDUSTRY",
    sortOrder: 3,
  },
  {
    id: "industry-ad-media-entertainment-game-anime-event",
    name: "ゲーム・アニメ・イベント",
    description: "ゲーム/アニメ/イベント",
    parentId: "industry-ad-media-entertainment",
    level: 2,
    taxonomyTypeCode: "INDUSTRY",
    sortOrder: 4,
  },

  // 2階層 - メディカル・ヘルスケア
  {
    id: "industry-medical-healthcare-pharmaceutical",
    name: "医薬品",
    description: "製薬/医薬品",
    parentId: "industry-medical-healthcare",
    level: 2,
    taxonomyTypeCode: "INDUSTRY",
    sortOrder: 1,
  },
  {
    id: "industry-medical-healthcare-bio",
    name: "バイオ",
    description: "バイオ関連",
    parentId: "industry-medical-healthcare",
    level: 2,
    taxonomyTypeCode: "INDUSTRY",
    sortOrder: 2,
  },
  {
    id: "industry-medical-healthcare-medical-device-maker",
    name: "医療機器メーカー",
    description: "医療機器メーカー",
    parentId: "industry-medical-healthcare",
    level: 2,
    taxonomyTypeCode: "INDUSTRY",
    sortOrder: 3,
  },
  {
    id: "industry-medical-healthcare-hospital-clinic",
    name: "病院・クリニック",
    description: "医療機関（病院/クリニック）",
    parentId: "industry-medical-healthcare",
    level: 2,
    taxonomyTypeCode: "INDUSTRY",
    sortOrder: 4,
  },
  {
    id: "industry-medical-healthcare-nursing-care-facility",
    name: "介護施設",
    description: "介護施設/介護事業者",
    parentId: "industry-medical-healthcare",
    level: 2,
    taxonomyTypeCode: "INDUSTRY",
    sortOrder: 5,
  },
  {
    id: "industry-medical-healthcare-drugstore-pharmacy",
    name: "ドラッグストア・調剤薬局",
    description: "ドラッグストア/調剤薬局",
    parentId: "industry-medical-healthcare",
    level: 2,
    taxonomyTypeCode: "INDUSTRY",
    sortOrder: 6,
  },

  // 2階層 - サービス・人材
  {
    id: "industry-service-hr-recruitment",
    name: "人材紹介",
    description: "人材紹介サービス",
    parentId: "industry-service-hr",
    level: 2,
    taxonomyTypeCode: "INDUSTRY",
    sortOrder: 1,
  },
  {
    id: "industry-service-hr-temporary-staffing",
    name: "派遣",
    description: "人材派遣",
    parentId: "industry-service-hr",
    level: 2,
    taxonomyTypeCode: "INDUSTRY",
    sortOrder: 2,
  },
  {
    id: "industry-service-hr-hr-service",
    name: "HRサービス",
    description: "HR関連サービス",
    parentId: "industry-service-hr",
    level: 2,
    taxonomyTypeCode: "INDUSTRY",
    sortOrder: 3,
  },
  {
    id: "industry-service-hr-education",
    name: "教育",
    description: "教育/研修サービス",
    parentId: "industry-service-hr",
    level: 2,
    taxonomyTypeCode: "INDUSTRY",
    sortOrder: 4,
  },
  {
    id: "industry-service-hr-hotel",
    name: "ホテル",
    description: "宿泊/ホテル",
    parentId: "industry-service-hr",
    level: 2,
    taxonomyTypeCode: "INDUSTRY",
    sortOrder: 5,
  },
  {
    id: "industry-service-hr-travel-tourism",
    name: "旅行・観光",
    description: "旅行/観光",
    parentId: "industry-service-hr",
    level: 2,
    taxonomyTypeCode: "INDUSTRY",
    sortOrder: 6,
  },
  {
    id: "industry-service-hr-outsourcing-bpo-callcenter",
    name: "アウトソーシング・BPO・コールセンター",
    description: "BPO/アウトソーシング/コールセンター",
    parentId: "industry-service-hr",
    level: 2,
    taxonomyTypeCode: "INDUSTRY",
    sortOrder: 7,
  },

  // 2階層 - 公共・その他
  {
    id: "industry-public-other-government",
    name: "官公庁・自治体",
    description: "官公庁/自治体",
    parentId: "industry-public-other",
    level: 2,
    taxonomyTypeCode: "INDUSTRY",
    sortOrder: 1,
  },
  {
    id: "industry-public-other-npo",
    name: "非営利団体（NPO等）",
    description: "NPO/非営利団体",
    parentId: "industry-public-other",
    level: 2,
    taxonomyTypeCode: "INDUSTRY",
    sortOrder: 2,
  },
  {
    id: "industry-public-other-primary-industry",
    name: "農林水産・鉱業",
    description: "一次産業/鉱業",
    parentId: "industry-public-other",
    level: 2,
    taxonomyTypeCode: "INDUSTRY",
    sortOrder: 3,
  },

  // =========================================================
  // 職種
  // =========================================================  
  {
    id: "job-management-bizdev",
    name: "経営・事業開発",
    description: "経営/事業開発/変革推進など",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 1,
  },
  {
    id: "job-corporate",
    name: "コーポレート（管理部門）",
    description: "人事/経理/法務/総務/SCMなど",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 2,
  },
  {
    id: "job-sales-cs",
    name: "営業・カスタマーサクセス",
    description: "営業/CS/サポートなど",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 3,
  },
  {
    id: "job-marketing-planning",
    name: "マーケティング・企画",
    description: "マーケ/リサーチ/商品企画など",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 4,
  },
  {
    id: "job-consultant-specialist",
    name: "コンサルタント・専門職",
    description: "コンサル/士業/講師など",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 5,
  },
  {
    id: "job-it-technology",
    name: "IT・テクノロジー",
    description: "PM/開発/データAI/インフラなど",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 6,
  },
  {
    id: "job-creative-design",
    name: "クリエイティブ・デザイン",
    description: "デザイン/制作/編集など",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 7,
  },
  {
    id: "job-manufacturing-engineering",
    name: "モノづくり（製造・エンジニアリング）",
    description: "設計/生産/品質/フィールドなど",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 8,
  },
  {
    id: "job-finance-realestate-construction",
    name: "金融・不動産・建設",
    description: "金融専門/不動産/建設など",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 9,
  },
  {
    id: "job-medical-pharma-bio",
    name: "医療・医薬・バイオ",
    description: "医療/医薬/バイオ領域の職種",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 10,
  },

  // 2階層 - 経営・事業開発
  {
    id: "job-management-bizdev-executive",
    name: "経営者・取締役・役員",
    description: "経営トップ/役員クラス",
    parentId: "job-management-bizdev",
    level: 2,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 1,
  },
  {
    id: "job-management-bizdev-corp-planning",
    name: "経営企画・事業統括",
    description: "経営企画/事業統括",
    parentId: "job-management-bizdev",
    level: 2,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 2,
  },
  {
    id: "job-management-bizdev-newbiz-bizdev",
    name: "新規事業企画・事業開発",
    description: "新規事業/事業開発",
    parentId: "job-management-bizdev",
    level: 2,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 3,
  },
  {
    id: "job-management-bizdev-dx",
    name: "DX推進",
    description: "DX推進/デジタル変革",
    parentId: "job-management-bizdev",
    level: 2,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 4,
  },
  {
    id: "job-management-bizdev-business-transformation",
    name: "業務変革",
    description: "業務改革/変革推進",
    parentId: "job-management-bizdev",
    level: 2,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 5,
  },
  {
    id: "job-management-bizdev-ma-alliance-pmi",
    name: "M&A・事業提携・PMI",
    description: "M&A/提携/PMI",
    parentId: "job-management-bizdev",
    level: 2,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 6,
  },

  // 2階層 - コーポレート（管理部門）
  {
    id: "job-corporate-hr",
    name: "人事・採用",
    description: "採用/育成/制度/労務など",
    parentId: "job-corporate",
    level: 2,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 1,
  },
  {
    id: "job-corporate-accounting-finance",
    name: "経理・財務",
    description: "経理/財務/税務/IRなど",
    parentId: "job-corporate",
    level: 2,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 2,
  },
  {
    id: "job-corporate-legal-ip",
    name: "法務・知財",
    description: "法務/コンプライアンス/知財など",
    parentId: "job-corporate",
    level: 2,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 3,
  },
  {
    id: "job-corporate-general-affairs",
    name: "総務・庶務",
    description: "総務/秘書/広報PRなど",
    parentId: "job-corporate",
    level: 2,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 4,
  },
  {
    id: "job-corporate-supply-chain",
    name: "サプライチェーン",
    description: "購買/物流/貿易事務など",
    parentId: "job-corporate",
    level: 2,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 5,
  },

  // 3階層 - 人事・採用
  {
    id: "job-corporate-hr-recruiting",
    name: "採用（新卒/中途）",
    description: "新卒/中途採用",
    parentId: "job-corporate-hr",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 1,
  },
  {
    id: "job-corporate-hr-talent-development",
    name: "人材開発・研修",
    description: "研修/育成/学習支援",
    parentId: "job-corporate-hr",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 2,
  },
  {
    id: "job-corporate-hr-hr-systems",
    name: "制度設計",
    description: "人事制度/評価制度設計",
    parentId: "job-corporate-hr",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 3,
  },
  {
    id: "job-corporate-hr-od",
    name: "組織開発（OD）",
    description: "組織開発/カルチャー施策",
    parentId: "job-corporate-hr",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 4,
  },
  {
    id: "job-corporate-hr-labor-payroll",
    name: "労務・給与",
    description: "労務/給与/社保など",
    parentId: "job-corporate-hr",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 5,
  },
  {
    id: "job-corporate-hr-hrbp",
    name: "HRBP",
    description: "HRBP",
    parentId: "job-corporate-hr",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 6,
  },

  // 3階層 - 経理・財務
  {
    id: "job-corporate-accounting-finance-accounting",
    name: "経理",
    description: "経理業務",
    parentId: "job-corporate-accounting-finance",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 1,
  },
  {
    id: "job-corporate-accounting-finance-finance",
    name: "財務",
    description: "資金調達/資金管理など",
    parentId: "job-corporate-accounting-finance",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 2,
  },
  {
    id: "job-corporate-accounting-finance-management-accounting",
    name: "管理会計",
    description: "管理会計/予実管理など",
    parentId: "job-corporate-accounting-finance",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 3,
  },
  {
    id: "job-corporate-accounting-finance-tax",
    name: "税務",
    description: "税務対応",
    parentId: "job-corporate-accounting-finance",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 4,
  },
  {
    id: "job-corporate-accounting-finance-ir",
    name: "IR",
    description: "IR/投資家対応",
    parentId: "job-corporate-accounting-finance",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 5,
  },

  // 3階層 - 法務・知財
  {
    id: "job-corporate-legal-ip-legal-compliance",
    name: "法務・コンプライアンス",
    description: "契約/法務/コンプライアンス",
    parentId: "job-corporate-legal-ip",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 1,
  },
  {
    id: "job-corporate-legal-ip-ip-patent",
    name: "知的財産・特許",
    description: "知財/特許",
    parentId: "job-corporate-legal-ip",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 2,
  },

  // 3階層 - 総務・庶務
  {
    id: "job-corporate-general-affairs-general-affairs",
    name: "総務",
    description: "総務業務",
    parentId: "job-corporate-general-affairs",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 1,
  },
  {
    id: "job-corporate-general-affairs-secretary",
    name: "秘書",
    description: "秘書業務",
    parentId: "job-corporate-general-affairs",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 2,
  },
  {
    id: "job-corporate-general-affairs-pr",
    name: "広報・PR",
    description: "広報/PR",
    parentId: "job-corporate-general-affairs",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 3,
  },

  // 3階層 - サプライチェーン
  {
    id: "job-corporate-supply-chain-procurement",
    name: "購買・資材調達",
    description: "購買/調達",
    parentId: "job-corporate-supply-chain",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 1,
  },
  {
    id: "job-corporate-supply-chain-logistics-inventory",
    name: "物流企画・在庫管理",
    description: "物流企画/在庫管理",
    parentId: "job-corporate-supply-chain",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 2,
  },
  {
    id: "job-corporate-supply-chain-trade-admin",
    name: "国際・貿易事務",
    description: "貿易/国際事務",
    parentId: "job-corporate-supply-chain",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 3,
  },

  // 2階層 - 営業・カスタマーサクセス
  {
    id: "job-sales-cs-front-sales",
    name: "フロント営業",
    description: "法人/個人/海外/代理店など",
    parentId: "job-sales-cs",
    level: 2,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 1,
  },
  {
    id: "job-sales-cs-sales-strategy-support",
    name: "営業戦略・支援",
    description: "営業企画/インサイド/プリセールス等",
    parentId: "job-sales-cs",
    level: 2,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 2,
  },
  {
    id: "job-sales-cs-customer-retention-support",
    name: "顧客維持・支援",
    description: "CS/サポート/コールセンター運営等",
    parentId: "job-sales-cs",
    level: 2,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 3,
  },

  // 3階層 - フロント営業
  {
    id: "job-sales-cs-front-sales-enterprise-corporate",
    name: "法人営業（大手/中堅）",
    description: "法人営業（大手/中堅向け）",
    parentId: "job-sales-cs-front-sales",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 1,
  },
  {
    id: "job-sales-cs-front-sales-individual",
    name: "個人営業",
    description: "個人向け営業",
    parentId: "job-sales-cs-front-sales",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 2,
  },
  {
    id: "job-sales-cs-front-sales-overseas",
    name: "海外営業",
    description: "海外向け営業",
    parentId: "job-sales-cs-front-sales",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 3,
  },
  {
    id: "job-sales-cs-front-sales-partner",
    name: "代理店営業・パートナーセールス",
    description: "代理店/パートナー営業",
    parentId: "job-sales-cs-front-sales",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 4,
  },

  // 3階層 - 営業戦略・支援
  {
    id: "job-sales-cs-sales-strategy-support-sales-planning",
    name: "営業企画",
    description: "営業企画",
    parentId: "job-sales-cs-sales-strategy-support",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 1,
  },
  {
    id: "job-sales-cs-sales-strategy-support-inside-sales",
    name: "インサイドセールス",
    description: "インサイドセールス",
    parentId: "job-sales-cs-sales-strategy-support",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 2,
  },
  {
    id: "job-sales-cs-sales-strategy-support-sales-admin-assistant",
    name: "営業事務・アシスタント",
    description: "営業事務/アシスタント",
    parentId: "job-sales-cs-sales-strategy-support",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 3,
  },
  {
    id: "job-sales-cs-sales-strategy-support-presales",
    name: "プリセールス（技術営業）",
    description: "技術営業/プリセールス",
    parentId: "job-sales-cs-sales-strategy-support",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 4,
  },

  // 3階層 - 顧客維持・支援
  {
    id: "job-sales-cs-customer-retention-support-customer-success",
    name: "カスタマーサクセス（CS）",
    description: "カスタマーサクセス",
    parentId: "job-sales-cs-customer-retention-support",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 1,
  },
  {
    id: "job-sales-cs-customer-retention-support-customer-support",
    name: "カスタマーサポート",
    description: "カスタマーサポート",
    parentId: "job-sales-cs-customer-retention-support",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 2,
  },
  {
    id: "job-sales-cs-customer-retention-support-callcenter-ops",
    name: "コールセンター運営",
    description: "コールセンター運営",
    parentId: "job-sales-cs-customer-retention-support",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 3,
  },

  // 2階層 - マーケティング・企画
  {
    id: "job-marketing-planning-marketing",
    name: "マーケティング",
    description: "デジマ/SNS/PRなど",
    parentId: "job-marketing-planning",
    level: 2,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 1,
  },
  {
    id: "job-marketing-planning-research-analysis",
    name: "リサーチ・分析",
    description: "市場調査/データ分析",
    parentId: "job-marketing-planning",
    level: 2,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 2,
  },
  {
    id: "job-marketing-planning-product-service-planning",
    name: "商品・サービス企画",
    description: "商品企画/販促/MD等",
    parentId: "job-marketing-planning",
    level: 2,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 3,
  },

  // 3階層 - マーケティング
  {
    id: "job-marketing-planning-marketing-digital-marketing",
    name: "デジタルマーケティング",
    description: "デジタルマーケティング",
    parentId: "job-marketing-planning-marketing",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 1,
  },
  {
    id: "job-marketing-planning-marketing-ads-seo",
    name: "広告運用・SEO",
    description: "広告運用/SEO",
    parentId: "job-marketing-planning-marketing",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 2,
  },
  {
    id: "job-marketing-planning-marketing-sns-marketing",
    name: "SNSマーケティング",
    description: "SNSマーケティング",
    parentId: "job-marketing-planning-marketing",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 3,
  },
  {
    id: "job-marketing-planning-marketing-pr",
    name: "広報・PR",
    description: "広報/PR",
    parentId: "job-marketing-planning-marketing",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 4,
  },

  // 3階層 - リサーチ・分析
  {
    id: "job-marketing-planning-research-analysis-market-research",
    name: "市場調査・リサーチ",
    description: "市場調査/リサーチ",
    parentId: "job-marketing-planning-research-analysis",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 1,
  },
  {
    id: "job-marketing-planning-research-analysis-data-analyst",
    name: "データ分析（アナリスト）",
    description: "データ分析/アナリスト",
    parentId: "job-marketing-planning-research-analysis",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 2,
  },

  // 3階層 - 商品・サービス企画
  {
    id: "job-marketing-planning-product-service-planning-product-dev",
    name: "商品企画・開発",
    description: "商品企画/開発",
    parentId: "job-marketing-planning-product-service-planning",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 1,
  },
  {
    id: "job-marketing-planning-product-service-planning-promotion",
    name: "販促・プロモーション",
    description: "販促/プロモーション",
    parentId: "job-marketing-planning-product-service-planning",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 2,
  },
  {
    id: "job-marketing-planning-product-service-planning-md-vmd",
    name: "MD・VMD",
    description: "MD/VMD",
    parentId: "job-marketing-planning-product-service-planning",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 3,
  },

  // 2階層 - コンサルタント・専門職
  {
    id: "job-consultant-specialist-consulting",
    name: "コンサル",
    description: "戦略/財務/人事/ITなど",
    parentId: "job-consultant-specialist",
    level: 2,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 1,
  },
  {
    id: "job-consultant-specialist-professional",
    name: "士業・専門職",
    description: "会計士/税理士/弁護士等",
    parentId: "job-consultant-specialist",
    level: 2,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 2,
  },

  // 3階層 - コンサル
  {
    id: "job-consultant-specialist-consulting-strategy",
    name: "戦略",
    description: "戦略コンサル",
    parentId: "job-consultant-specialist-consulting",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 1,
  },
  {
    id: "job-consultant-specialist-consulting-finance-accounting",
    name: "財務・会計",
    description: "財務/会計コンサル",
    parentId: "job-consultant-specialist-consulting",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 2,
  },
  {
    id: "job-consultant-specialist-consulting-hr-org",
    name: "組織・人事",
    description: "組織/人事コンサル",
    parentId: "job-consultant-specialist-consulting",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 3,
  },
  {
    id: "job-consultant-specialist-consulting-bpr",
    name: "業務プロセス（BPR）",
    description: "BPR/業務改革コンサル",
    parentId: "job-consultant-specialist-consulting",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 4,
  },
  {
    id: "job-consultant-specialist-consulting-it",
    name: "ITコンサル",
    description: "ITコンサル",
    parentId: "job-consultant-specialist-consulting",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 5,
  },

  // 3階層 - 士業・専門職
  {
    id: "job-consultant-specialist-professional-cpa",
    name: "公認会計士",
    description: "公認会計士",
    parentId: "job-consultant-specialist-professional",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 1,
  },
  {
    id: "job-consultant-specialist-professional-tax-accountant",
    name: "税理士",
    description: "税理士",
    parentId: "job-consultant-specialist-professional",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 2,
  },
  {
    id: "job-consultant-specialist-professional-lawyer",
    name: "弁護士",
    description: "弁護士",
    parentId: "job-consultant-specialist-professional",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 3,
  },
  {
    id: "job-consultant-specialist-professional-patent-attorney",
    name: "弁理士",
    description: "弁理士",
    parentId: "job-consultant-specialist-professional",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 4,
  },
  {
    id: "job-consultant-specialist-professional-administrative-scrivener",
    name: "行政書士",
    description: "行政書士",
    parentId: "job-consultant-specialist-professional",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 5,
  },
  {
    id: "job-consultant-specialist-professional-teacher-lecturer",
    name: "講師・教諭",
    description: "講師/教諭",
    parentId: "job-consultant-specialist-professional",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 6,
  },

  // 2階層 - IT・テクノロジー
  {
    id: "job-it-technology-pm-planning",
    name: "PM・企画",
    description: "PM/PdM/アーキテクトなど",
    parentId: "job-it-technology",
    level: 2,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 1,
  },
  {
    id: "job-it-technology-development",
    name: "開発",
    description: "フロント/バック/アプリ等",
    parentId: "job-it-technology",
    level: 2,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 2,
  },
  {
    id: "job-it-technology-data-ai",
    name: "データ・AI",
    description: "DS/ML/DBなど",
    parentId: "job-it-technology",
    level: 2,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 3,
  },
  {
    id: "job-it-technology-infra-security",
    name: "インフラ・セキュリティ",
    description: "インフラ/ネットワーク/セキュリティ等",
    parentId: "job-it-technology",
    level: 2,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 4,
  },
  {
    id: "job-it-technology-ops-maintenance",
    name: "運用・保守",
    description: "社内SE/テクサポ/QA等",
    parentId: "job-it-technology",
    level: 2,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 5,
  },

  // 3階層 - PM・企画
  {
    id: "job-it-technology-pm-planning-project-manager",
    name: "プロジェクトマネージャー（PM）",
    description: "プロジェクトマネージャー",
    parentId: "job-it-technology-pm-planning",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 1,
  },
  {
    id: "job-it-technology-pm-planning-product-manager",
    name: "プロダクトマネージャー（PdM）",
    description: "プロダクトマネージャー",
    parentId: "job-it-technology-pm-planning",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 2,
  },
  {
    id: "job-it-technology-pm-planning-it-architect",
    name: "ITアーキテクト",
    description: "ITアーキテクト",
    parentId: "job-it-technology-pm-planning",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 3,
  },

  // 3階層 - 開発
  {
    id: "job-it-technology-development-frontend",
    name: "フロントエンド",
    description: "フロントエンド開発",
    parentId: "job-it-technology-development",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 1,
  },
  {
    id: "job-it-technology-development-backend",
    name: "バックエンド（Web/オープン系）",
    description: "バックエンド開発",
    parentId: "job-it-technology-development",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 2,
  },
  {
    id: "job-it-technology-development-mobile-app",
    name: "スマートフォンアプリ",
    description: "スマホアプリ開発",
    parentId: "job-it-technology-development",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 3,
  },
  {
    id: "job-it-technology-development-game-dev",
    name: "ゲーム開発",
    description: "ゲーム開発",
    parentId: "job-it-technology-development",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 4,
  },
  {
    id: "job-it-technology-development-embedded-control",
    name: "組み込み・制御",
    description: "組み込み/制御開発",
    parentId: "job-it-technology-development",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 5,
  },

  // 3階層 - データ・AI
  {
    id: "job-it-technology-data-ai-data-scientist",
    name: "データサイエンティスト",
    description: "データサイエンティスト",
    parentId: "job-it-technology-data-ai",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 1,
  },
  {
    id: "job-it-technology-data-ai-ml-engineer",
    name: "機械学習エンジニア",
    description: "機械学習エンジニア",
    parentId: "job-it-technology-data-ai",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 2,
  },
  {
    id: "job-it-technology-data-ai-db-engineer",
    name: "データベースエンジニア",
    description: "DBエンジニア",
    parentId: "job-it-technology-data-ai",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 3,
  },

  // 3階層 - インフラ・セキュリティ
  {
    id: "job-it-technology-infra-security-infra-engineer",
    name: "インフラエンジニア",
    description: "インフラエンジニア",
    parentId: "job-it-technology-infra-security",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 1,
  },
  {
    id: "job-it-technology-infra-security-server-network",
    name: "サーバー・ネットワーク",
    description: "サーバー/ネットワーク",
    parentId: "job-it-technology-infra-security",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 2,
  },
  {
    id: "job-it-technology-infra-security-security-engineer",
    name: "セキュリティエンジニア",
    description: "セキュリティエンジニア",
    parentId: "job-it-technology-infra-security",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 3,
  },

  // 3階層 - 運用・保守
  {
    id: "job-it-technology-ops-maintenance-inhouse-se",
    name: "社内SE・情報システム",
    description: "社内SE/情シス",
    parentId: "job-it-technology-ops-maintenance",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 1,
  },
  {
    id: "job-it-technology-ops-maintenance-tech-support",
    name: "テクニカルサポート",
    description: "テクニカルサポート",
    parentId: "job-it-technology-ops-maintenance",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 2,
  },
  {
    id: "job-it-technology-ops-maintenance-qa-test",
    name: "QA・テスト",
    description: "QA/テスト",
    parentId: "job-it-technology-ops-maintenance",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 3,
  },

  // 2階層 - クリエイティブ・デザイン
  {
    id: "job-creative-design-design",
    name: "デザイン",
    description: "UI/UX/Web/グラフィック等",
    parentId: "job-creative-design",
    level: 2,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 1,
  },
  {
    id: "job-creative-design-editing-production",
    name: "編集・制作",
    description: "ディレクション/編集/制作等",
    parentId: "job-creative-design",
    level: 2,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 2,
  },

  // 3階層 - デザイン
  {
    id: "job-creative-design-design-uiux",
    name: "UI/UXデザイナー",
    description: "UI/UXデザイン",
    parentId: "job-creative-design-design",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 1,
  },
  {
    id: "job-creative-design-design-web-designer",
    name: "Webデザイナー",
    description: "Webデザイン",
    parentId: "job-creative-design-design",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 2,
  },
  {
    id: "job-creative-design-design-art-director",
    name: "アートディレクター",
    description: "アートディレクション",
    parentId: "job-creative-design-design",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 3,
  },
  {
    id: "job-creative-design-design-graphic-designer",
    name: "グラフィックデザイナー",
    description: "グラフィックデザイン",
    parentId: "job-creative-design-design",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 4,
  },

  // 3階層 - 編集・制作
  {
    id: "job-creative-design-editing-production-web-director",
    name: "Webディレクター",
    description: "Webディレクション",
    parentId: "job-creative-design-editing-production",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 1,
  },
  {
    id: "job-creative-design-editing-production-content-editor",
    name: "コンテンツ企画・編集",
    description: "コンテンツ企画/編集",
    parentId: "job-creative-design-editing-production",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 2,
  },
  {
    id: "job-creative-design-editing-production-writer-reporter",
    name: "ライター・記者",
    description: "執筆/取材",
    parentId: "job-creative-design-editing-production",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 3,
  },
  {
    id: "job-creative-design-editing-production-video-editor",
    name: "映像制作・編集",
    description: "映像制作/編集",
    parentId: "job-creative-design-editing-production",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 4,
  },
  {
    id: "job-creative-design-editing-production-copywriter",
    name: "コピーライター",
    description: "コピーライティング",
    parentId: "job-creative-design-editing-production",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 5,
  },

  // 2階層 - モノづくり（製造・エンジニアリング）
  {
    id: "job-manufacturing-engineering-design-development",
    name: "設計・開発",
    description: "R&D/回路/機械/制御など",
    parentId: "job-manufacturing-engineering",
    level: 2,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 1,
  },
  {
    id: "job-manufacturing-engineering-production-quality",
    name: "生産・品質",
    description: "生産技術/生産管理/品質保証など",
    parentId: "job-manufacturing-engineering",
    level: 2,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 2,
  },
  {
    id: "job-manufacturing-engineering-field",
    name: "フィールド",
    description: "セールス/サービスエンジニアなど",
    parentId: "job-manufacturing-engineering",
    level: 2,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 3,
  },

  // 3階層 - 設計・開発
  {
    id: "job-manufacturing-engineering-design-development-rd",
    name: "研究・開発（R&D）",
    description: "研究開発",
    parentId: "job-manufacturing-engineering-design-development",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 1,
  },
  {
    id: "job-manufacturing-engineering-design-development-circuit-implementation",
    name: "回路・実装設計",
    description: "回路/実装設計",
    parentId: "job-manufacturing-engineering-design-development",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 2,
  },
  {
    id: "job-manufacturing-engineering-design-development-mechanical-housing",
    name: "機械・筐体設計",
    description: "機械/筐体設計",
    parentId: "job-manufacturing-engineering-design-development",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 3,
  },
  {
    id: "job-manufacturing-engineering-design-development-control-design",
    name: "制御設計",
    description: "制御設計",
    parentId: "job-manufacturing-engineering-design-development",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 4,
  },

  // 3階層 - 生産・品質
  {
    id: "job-manufacturing-engineering-production-quality-production-tech",
    name: "生産技術・プロセス開発",
    description: "生産技術/プロセス開発",
    parentId: "job-manufacturing-engineering-production-quality",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 1,
  },
  {
    id: "job-manufacturing-engineering-production-quality-production-control",
    name: "生産管理",
    description: "生産管理",
    parentId: "job-manufacturing-engineering-production-quality",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 2,
  },
  {
    id: "job-manufacturing-engineering-production-quality-quality-assurance",
    name: "品質管理・品質保証",
    description: "品質管理/品質保証",
    parentId: "job-manufacturing-engineering-production-quality",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 3,
  },
  {
    id: "job-manufacturing-engineering-production-quality-factory-manager",
    name: "工場長・プラント管理",
    description: "工場長/プラント管理",
    parentId: "job-manufacturing-engineering-production-quality",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 4,
  },

  // 3階層 - フィールド
  {
    id: "job-manufacturing-engineering-field-sales-engineer",
    name: "セールスエンジニア",
    description: "セールスエンジニア",
    parentId: "job-manufacturing-engineering-field",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 1,
  },
  {
    id: "job-manufacturing-engineering-field-service-engineer",
    name: "サービスエンジニア（保守・修理）",
    description: "保守/修理（サービスエンジニア）",
    parentId: "job-manufacturing-engineering-field",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 2,
  },

  // 2階層 - 金融・不動産・建設
  {
    id: "job-finance-realestate-construction-finance-specialist",
    name: "金融専門",
    description: "ディーラー/ファンド/融資審査など",
    parentId: "job-finance-realestate-construction",
    level: 2,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 1,
  },
  {
    id: "job-finance-realestate-construction-realestate",
    name: "不動産",
    description: "不動産開発/AM/PMなど",
    parentId: "job-finance-realestate-construction",
    level: 2,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 2,
  },
  {
    id: "job-finance-realestate-construction-construction-civil",
    name: "建設・土木",
    description: "設計/施工管理/測量など",
    parentId: "job-finance-realestate-construction",
    level: 2,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 3,
  },

  // 3階層 - 金融専門
  {
    id: "job-finance-realestate-construction-finance-specialist-dealer-trader",
    name: "ディーラー・トレーダー",
    description: "ディーラー/トレーダー",
    parentId: "job-finance-realestate-construction-finance-specialist",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 1,
  },
  {
    id: "job-finance-realestate-construction-finance-specialist-fund-manager",
    name: "ファンドマネージャー",
    description: "ファンドマネージャー",
    parentId: "job-finance-realestate-construction-finance-specialist",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 2,
  },
  {
    id: "job-finance-realestate-construction-finance-specialist-analyst",
    name: "アナリスト",
    description: "アナリスト",
    parentId: "job-finance-realestate-construction-finance-specialist",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 3,
  },
  {
    id: "job-finance-realestate-construction-finance-specialist-loan-screening-risk",
    name: "融資審査・リスク管理",
    description: "融資審査/リスク管理",
    parentId: "job-finance-realestate-construction-finance-specialist",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 4,
  },

  // 3階層 - 不動産
  {
    id: "job-finance-realestate-construction-realestate-planning-development",
    name: "不動産企画・開発",
    description: "不動産企画/開発",
    parentId: "job-finance-realestate-construction-realestate",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 1,
  },
  {
    id: "job-finance-realestate-construction-realestate-land-acquisition",
    name: "用地仕入",
    description: "用地仕入",
    parentId: "job-finance-realestate-construction-realestate",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 2,
  },
  {
    id: "job-finance-realestate-construction-realestate-asset-management",
    name: "アセットマネジメント",
    description: "アセットマネジメント",
    parentId: "job-finance-realestate-construction-realestate",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 3,
  },
  {
    id: "job-finance-realestate-construction-realestate-property-management",
    name: "プロパティマネジメント",
    description: "プロパティマネジメント",
    parentId: "job-finance-realestate-construction-realestate",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 4,
  },

  // 3階層 - 建設・土木
  {
    id: "job-finance-realestate-construction-construction-civil-architectural-design-estimation",
    name: "建築設計・積算",
    description: "建築設計/積算",
    parentId: "job-finance-realestate-construction-construction-civil",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 1,
  },
  {
    id: "job-finance-realestate-construction-construction-civil-construction-management",
    name: "施工管理（建築/土木/設備）",
    description: "施工管理",
    parentId: "job-finance-realestate-construction-construction-civil",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 2,
  },
  {
    id: "job-finance-realestate-construction-construction-civil-survey-structural-analysis",
    name: "測量・構造解析",
    description: "測量/構造解析",
    parentId: "job-finance-realestate-construction-construction-civil",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 3,
  },

  // 2階層 - 医療・医薬・バイオ
  {
    id: "job-medical-pharma-bio-sales-planning",
    name: "営業・企画",
    description: "MR/医療機器/薬事など",
    parentId: "job-medical-pharma-bio",
    level: 2,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 1,
  },
  {
    id: "job-medical-pharma-bio-rd",
    name: "開発・研究",
    description: "CRA/統計解析/薬理研究など",
    parentId: "job-medical-pharma-bio",
    level: 2,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 2,
  },
  {
    id: "job-medical-pharma-bio-professional",
    name: "専門職",
    description: "医師/看護師/薬剤師など",
    parentId: "job-medical-pharma-bio",
    level: 2,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 3,
  },

  // 3階層 - 営業・企画
  {
    id: "job-medical-pharma-bio-sales-planning-mr",
    name: "MR（医薬情報担当者）",
    description: "MR",
    parentId: "job-medical-pharma-bio-sales-planning",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 1,
  },
  {
    id: "job-medical-pharma-bio-sales-planning-medical-device-sales",
    name: "医療機器営業",
    description: "医療機器営業",
    parentId: "job-medical-pharma-bio-sales-planning",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 2,
  },
  {
    id: "job-medical-pharma-bio-sales-planning-msl",
    name: "MSL",
    description: "MSL",
    parentId: "job-medical-pharma-bio-sales-planning",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 3,
  },
  {
    id: "job-medical-pharma-bio-sales-planning-regulatory-pms",
    name: "薬事・市販後調査",
    description: "薬事/市販後調査",
    parentId: "job-medical-pharma-bio-sales-planning",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 4,
  },

  // 3階層 - 開発・研究
  {
    id: "job-medical-pharma-bio-rd-cra",
    name: "非臨床・臨床開発（CRA）",
    description: "臨床開発/CRA",
    parentId: "job-medical-pharma-bio-rd",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 1,
  },
  {
    id: "job-medical-pharma-bio-rd-statistical-analysis",
    name: "統計解析",
    description: "統計解析",
    parentId: "job-medical-pharma-bio-rd",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 2,
  },
  {
    id: "job-medical-pharma-bio-rd-pharmacology-research",
    name: "薬理研究",
    description: "薬理研究",
    parentId: "job-medical-pharma-bio-rd",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 3,
  },

  // 3階層 - 専門職
  {
    id: "job-medical-pharma-bio-professional-doctor",
    name: "医師",
    description: "医師",
    parentId: "job-medical-pharma-bio-professional",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 1,
  },
  {
    id: "job-medical-pharma-bio-professional-nurse",
    name: "看護師",
    description: "看護師",
    parentId: "job-medical-pharma-bio-professional",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 2,
  },
  {
    id: "job-medical-pharma-bio-professional-pharmacist",
    name: "薬剤師",
    description: "薬剤師",
    parentId: "job-medical-pharma-bio-professional",
    level: 3,
    taxonomyTypeCode: "JOB_CATEGORY",
    sortOrder: 3,
  },

  // =========================================================
  // 役割 / 立場
  // =========================================================
  {
    id: "position-executive",
    name: "経営者・役員",
    description: "経営トップ/役員",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "POSITION",
    sortOrder: 1,
  },
  {
    id: "position-business-head",
    name: "事業責任者・部門長",
    description: "事業責任者/部門長",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "POSITION",
    sortOrder: 2,
  },
  {
    id: "position-director",
    name: "部長",
    description: "部長クラス",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "POSITION",
    sortOrder: 3,
  },
  {
    id: "position-manager",
    name: "マネージャー/課長",
    description: "マネージャー/課長クラス",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "POSITION",
    sortOrder: 4,
  },
  {
    id: "position-store-manager",
    name: "店長",
    description: "店長",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "POSITION",
    sortOrder: 5,
  },
  {
    id: "position-section-chief",
    name: "係長",
    description: "係長クラス",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "POSITION",
    sortOrder: 6,
  },
  {
    id: "position-leader",
    name: "リーダー",
    description: "チームリーダー",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "POSITION",
    sortOrder: 7,
  },
  {
    id: "position-pm-leader",
    name: "プロジェクトマネージャー/リーダー",
    description: "PM/プロジェクトリーダー",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "POSITION",
    sortOrder: 8,
  },
  {
    id: "position-mid-career",
    name: "中堅層",
    description: "中堅層",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "POSITION",
    sortOrder: 9,
  },
  {
    id: "position-specialist",
    name: "スペシャリスト",
    description: "専門職/エキスパート",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "POSITION",
    sortOrder: 10,
  },
  {
    id: "position-young",
    name: "若手層",
    description: "若手層",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "POSITION",
    sortOrder: 11,
  },
  {
    id: "position-freelance",
    name: "フリーランス・個人事業主",
    description: "フリーランス/個人事業主",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "POSITION",
    sortOrder: 12,
  },
  {
    id: "position-sidejob-partner",
    name: "副業・パートナー",
    description: "副業/業務委託/パートナー",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "POSITION",
    sortOrder: 13,
  },
  {
    id: "position-successor",
    name: "後継者",
    description: "後継者",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "POSITION",
    sortOrder: 14,
  },
  {
    id: "position-other",
    name: "その他（特殊・状況的な立場）",
    description: "その他の立場",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "POSITION",
    sortOrder: 15,
  },

  // =========================================================
  // 状況
  // =========================================================
  {
    id: "situation-large",
    name: "大手企業",
    description: "大企業/上場企業クラス",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "SITUATION",
    sortOrder: 1,
  },
  {
    id: "situation-mid",
    name: "中堅企業",
    description: "中堅企業",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "SITUATION",
    sortOrder: 2,
  },
  {
    id: "situation-venture",
    name: "ベンチャー企業",
    description: "ベンチャー企業",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "SITUATION",
    sortOrder: 3,
  },
  {
    id: "situation-startup",
    name: "スタートアップ企業",
    description: "スタートアップ企業",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "SITUATION",
    sortOrder: 4,
  },
  {
    id: "situation-black",
    name: "ブラック環境",
    description: "労働環境が厳しい",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "SITUATION",
    sortOrder: 5,
  },
  {
    id: "situation-too-white",
    name: "ホワイト過ぎる",
    description: "ホワイト過ぎる環境",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "SITUATION",
    sortOrder: 6,
  },
  {
    id: "situation-family-owned",
    name: "同族経営 / オーナー企業",
    description: "同族/オーナー企業",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "SITUATION",
    sortOrder: 7,
  },
  {
    id: "situation-big-company-disease",
    name: "大企業病",
    description: "大企業特有の弊害",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "SITUATION",
    sortOrder: 8,
  },
  {
    id: "situation-firefighting",
    name: "炎上",
    description: "プロジェクト/業務が炎上",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "SITUATION",
    sortOrder: 9,
  },
  {
    id: "situation-internal-conflict",
    name: "社内紛争 / 政治",
    description: "社内政治/対立",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "SITUATION",
    sortOrder: 10,
  },
  {
    id: "situation-harassment",
    name: "ハラスメント",
    description: "ハラスメント",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "SITUATION",
    sortOrder: 11,
  },
  {
    id: "situation-layoff",
    name: "リストラ",
    description: "リストラ",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "SITUATION",
    sortOrder: 12,
  },
  {
    id: "situation-business-withdrawal",
    name: "事業撤退",
    description: "事業撤退",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "SITUATION",
    sortOrder: 13,
  },
  {
    id: "situation-turnaround",
    name: "事業再生 / 立て直し",
    description: "再生/立て直し",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "SITUATION",
    sortOrder: 14,
  },
  {
    id: "situation-employment",
    name: "就職",
    description: "就職",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "SITUATION",
    sortOrder: 15,
  },
  {
    id: "situation-job-hunting",
    name: "転職活動",
    description: "転職活動",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "SITUATION",
    sortOrder: 16,
  },
  {
    id: "situation-resignation",
    name: "退職",
    description: "退職",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "SITUATION",
    sortOrder: 17,
  },
  {
    id: "situation-secondment",
    name: "出向",
    description: "出向",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "SITUATION",
    sortOrder: 18,
  },
  {
    id: "situation-transfer",
    name: "転籍",
    description: "転籍",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "SITUATION",
    sortOrder: 19,
  },
  {
    id: "situation-parachute-appointment",
    name: "天下り",
    description: "天下り",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "SITUATION",
    sortOrder: 20,
  },
  {
    id: "situation-internal-move",
    name: "異動",
    description: "異動",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "SITUATION",
    sortOrder: 21,
  },
  {
    id: "situation-expatriate",
    name: "駐在",
    description: "海外駐在",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "SITUATION",
    sortOrder: 22,
  },
  {
    id: "situation-work-abroad",
    name: "海外勤務",
    description: "海外勤務",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "SITUATION",
    sortOrder: 23,
  },
  {
    id: "situation-business-trip",
    name: "出張",
    description: "出張",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "SITUATION",
    sortOrder: 24,
  },
  {
    id: "situation-mental-health",
    name: "メンタルヘルス",
    description: "メンタルヘルス",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "SITUATION",
    sortOrder: 25,
  },
  {
    id: "situation-burnout",
    name: "燃え尽き",
    description: "燃え尽き",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "SITUATION",
    sortOrder: 26,
  },
  {
    id: "situation-karoshi",
    name: "過労死",
    description: "過労死",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "SITUATION",
    sortOrder: 27,
  },
  {
    id: "situation-limit-break",
    name: "限界突破",
    description: "限界突破",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "SITUATION",
    sortOrder: 28,
  },
  {
    id: "situation-window-seat",
    name: "窓際社員",
    description: "窓際社員",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "SITUATION",
    sortOrder: 29,
  },
  {
    id: "situation-corporate-slave",
    name: "社畜",
    description: "社畜",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "SITUATION",
    sortOrder: 30,
  },
  {
    id: "situation-thought-stopped",
    name: "思考停止",
    description: "思考停止",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "SITUATION",
    sortOrder: 31,
  },
  {
    id: "situation-disposable-soldier",
    name: "ソルジャー / 使い捨て",
    description: "使い捨て/ソルジャー",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "SITUATION",
    sortOrder: 32,
  },
  {
    id: "situation-office-romance",
    name: "社内恋愛",
    description: "社内恋愛",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "SITUATION",
    sortOrder: 33,
  },
  {
    id: "situation-generation-gap",
    name: "世代間ギャップ",
    description: "世代間ギャップ",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "SITUATION",
    sortOrder: 34,
  },
  {
    id: "situation-old-harm",
    name: "老害",
    description: "老害",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "SITUATION",
    sortOrder: 35,
  },
  {
    id: "situation-reading-the-air",
    name: "忖度 / 同調圧力",
    description: "忖度/同調圧力",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "SITUATION",
    sortOrder: 36,
  },
  {
    id: "situation-one-person-ops",
    name: "ワンオペ",
    description: "ワンオペ",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "SITUATION",
    sortOrder: 37,
  },
  {
    id: "situation-bus-factor",
    name: "属人化",
    description: "属人化",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "SITUATION",
    sortOrder: 38,
  },

  // =========================================================
  // スキル / メソッド
  // =========================================================
  {
    id: "skill-sales",
    name: "営業",
    description: "営業スキル/セールス手法",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "SKILL_METHOD",
    sortOrder: 1,
  },
  {
    id: "skill-logical-thinking",
    name: "ロジカルシンキング",
    description: "論理的思考/構造化",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "SKILL_METHOD",
    sortOrder: 2,
  },
  {
    id: "skill-structuring",
    name: "構造化",
    description: "情報/思考の構造化",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "SKILL_METHOD",
    sortOrder: 3,
  },
  {
    id: "skill-hypothesis-building",
    name: "仮説構築",
    description: "仮説構築",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "SKILL_METHOD",
    sortOrder: 4,
  },
  {
    id: "skill-critical-thinking",
    name: "クリティカルシンキング",
    description: "批判的思考",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "SKILL_METHOD",
    sortOrder: 5,
  },
  {
    id: "skill-design-thinking",
    name: "デザイン思考",
    description: "デザイン思考",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "SKILL_METHOD",
    sortOrder: 6,
  },
  {
    id: "skill-verbalization",
    name: "言語化",
    description: "言語化/説明力",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "SKILL_METHOD",
    sortOrder: 7,
  },
  {
    id: "skill-negotiation",
    name: "交渉",
    description: "交渉",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "SKILL_METHOD",
    sortOrder: 8,
  },
  {
    id: "skill-facilitation",
    name: "ファシリテーション",
    description: "会議/合意形成の推進",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "SKILL_METHOD",
    sortOrder: 9,
  },
  {
    id: "skill-coordination",
    name: "調整",
    description: "関係者調整",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "SKILL_METHOD",
    sortOrder: 10,
  },
  {
    id: "skill-presentation",
    name: "プレゼンテーション",
    description: "プレゼンテーション",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "SKILL_METHOD",
    sortOrder: 11,
  },
  {
    id: "skill-management",
    name: "マネジメント",
    description: "マネジメント",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "SKILL_METHOD",
    sortOrder: 12,
  },
  {
    id: "skill-education-mentoring",
    name: "教育・育成",
    description: "教育/育成/メンタリング",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "SKILL_METHOD",
    sortOrder: 13,
  },
  {
    id: "skill-coaching",
    name: "コーチング",
    description: "コーチング",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "SKILL_METHOD",
    sortOrder: 14,
  },
  {
    id: "skill-decision-making",
    name: "意思決定",
    description: "意思決定",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "SKILL_METHOD",
    sortOrder: 15,
  },
  {
    id: "skill-stakeholder-engagement",
    name: "巻き込み",
    description: "巻き込み/関係者の推進",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "SKILL_METHOD",
    sortOrder: 16,
  },
  {
    id: "skill-analysis",
    name: "分析",
    description: "分析",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "SKILL_METHOD",
    sortOrder: 17,
  },
  {
    id: "skill-project-management",
    name: "プロジェクトマネジメント",
    description: "プロジェクト推進/管理",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "SKILL_METHOD",
    sortOrder: 18,
  },
  {
    id: "skill-new-business",
    name: "新規事業",
    description: "新規事業",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "SKILL_METHOD",
    sortOrder: 19,
  },
  {
    id: "skill-startup",
    name: "起業",
    description: "起業",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "SKILL_METHOD",
    sortOrder: 20,
  },
  {
    id: "skill-retrospective",
    name: "振り返り",
    description: "振り返り/改善",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "SKILL_METHOD",
    sortOrder: 21,
  },
  {
    id: "skill-business-management",
    name: "経営",
    description: "経営",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "SKILL_METHOD",
    sortOrder: 22,
  },
  {
    id: "skill-task-management",
    name: "タスクマネジメント",
    description: "タスク管理",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "SKILL_METHOD",
    sortOrder: 23,
  },
  {
    id: "skill-risk-management",
    name: "リスク管理",
    description: "リスク管理",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "SKILL_METHOD",
    sortOrder: 24,
  },
  {
    id: "skill-leadership",
    name: "リーダーシップ",
    description: "リーダーシップ",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "SKILL_METHOD",
    sortOrder: 25,
  },
  {
    id: "skill-internal-politics",
    name: "社内政治力",
    description: "社内調整/政治力",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "SKILL_METHOD",
    sortOrder: 26,
  },
  {
    id: "skill-goal-setting-feedback",
    name: "目標設定、評価・フィードバック",
    description: "目標設定/評価/フィードバック",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "SKILL_METHOD",
    sortOrder: 27,
  },
  {
    id: "skill-language",
    name: "語学",
    description: "語学",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "SKILL_METHOD",
    sortOrder: 28,
  },

  // =========================================================
  // ナレッジ
  // =========================================================
  {
    id: "knowledge-role",
    name: "職種ナレッジ",
    description: "職種に紐づく知識",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "KNOWLEDGE",
    sortOrder: 1,
  },
  {
    id: "knowledge-trend",
    name: "トレンド",
    description: "トレンド知識",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "KNOWLEDGE",
    sortOrder: 2,
  },
  {
    id: "knowledge-industry",
    name: "業界ナレッジ",
    description: "業界に関する知識",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "KNOWLEDGE",
    sortOrder: 3,
  },
  {
    id: "knowledge-competitor",
    name: "競合ナレッジ",
    description: "競合に関する知識",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "KNOWLEDGE",
    sortOrder: 4,
  },
  {
    id: "knowledge-regulation",
    name: "法規制",
    description: "法規制/ルールに関する知識",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "KNOWLEDGE",
    sortOrder: 5,
  },
  {
    id: "knowledge-it",
    name: "IT",
    description: "ITに関する知識",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "KNOWLEDGE",
    sortOrder: 6,
  },
  {
    id: "knowledge-ai",
    name: "AI",
    description: "AIに関する知識",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "KNOWLEDGE",
    sortOrder: 7,
  },
  {
    id: "knowledge-qualification",
    name: "資格知識",
    description: "資格に関する知識",
    parentId: null,
    level: 1,
    taxonomyTypeCode: "KNOWLEDGE",
    sortOrder: 8,
  },
];
