import type { Metadata } from "next";

import "./globals.css";

import { Noto_Sans_JP } from "next/font/google";
import Script from "next/script";
import { themeInitScript } from "@/shared";

export const metadata: Metadata = {
  title: "Works Logue",
  description: "Generated by create next app",
};

const notoSansJP = Noto_Sans_JP({
  subsets: ["latin"],
  weight: ["400", "600"],
  variable: "--font-noto-sans-jp",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" className={notoSansJP.variable}>
      <head>
        <Script
          id="theme-init"
          strategy="beforeInteractive"
          dangerouslySetInnerHTML={{ __html: themeInitScript }}
        />
      </head>
      <body>{children}</body>
    </html>
  );
}
