import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Works Logue",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <header className="bg-purple-200 p-4">Works Logue</header>
        {children}
      </body>
    </html>
  );
}
